paion-data/astraios

src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java

Changelog
---------
- Change the CORS filter to support adding headers for Patch requests to support cross-domain operations for Patch requests
Checklist
---------

Fix patch request CORE error

---

.github/workflows/ci-cd.yml

Changelog
---------
- Added OAuth filter config in order to enable ES384 token validator
Checklist
---------

Add OAuth runtime config

---

src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy

Changelog
---------
- Add tests related to data paging for GraphQl
Checklist
---------

Add GraphQL paging tests

---

.github/actions/setup/action.yml
.github/workflows/ci-cd.yml

Changelog
---------
- Post enhancement of https://github.com/paion-data/astraios/pull/34
Checklist
---------

Change WAR file pick up location in order to fit a general deployment pattern

---

.mdlrc
README.md

Changelog
---------
Checklist
---------

Add demo video

---

src/test/groovy/com/paiondata/astraios/application/DockerComposeITSpec.groovy

Changelog
---------
Checklist
---------

Fix deployment error

---

.github/actions/setup/action.yml
.github/workflows/ci-cd.yml

Changelog
---------
Checklist
---------

Make data model a runtime injection

---

.github/actions/setup/action.yml
.github/workflows/ci-cd.yml
docs/docs/development.md
docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/elide.md
pom.xml
src/test/groovy/com/paiondata/astraios/application/DockerComposeITSpec.groovy

Changelog
---------
Checklist
---------

Externalize test data model

---

.github/workflows/contributors.yml
README.md
docs/README.md

Changelog
---------
Checklist
---------

Add contributors list

---

docs/docs/development.md
src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java

Changelog
---------
Checklist
---------
Reference
---------
- [Jersey 2.3 Setting Priority for ContainerRequestFilter](https://stackoverflow.com/a/26991667)

Request should hit CORS filter first

---

docs/docs/development.md

Changelog
---------
Checklist
---------
Reference
---------
- [Connect to mysql in a docker container from the host](https://stackoverflow.com/a/34489879)

Document how to access dockerized MySQL in development

---

README.md

Changelog
---------
Checklist
---------

Specify min EC2 size

---

README.md

Changelog
---------
Checklist
---------

Relocate EC2 badge

---

docker-compose.yml

Changelog
---------
Checklist
---------

Support UTF8 in Docker Compose DB

---

docs/docs/development.md
pom.xml

Changelog
---------
Checklist
---------

Simplify model package variable namings

---

src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy

Changelog
---------
Checklist
---------
Reference
---------
- [Serializes map to JSON in Groovy Spock](https://stackoverflow.com/a/51069031)

Enhance tests

---

.github/workflows/ci-cd.yml
docs/docs/development.md

Changelog
---------
Checklist
---------

Update internal data model repo name

---

.github/actions/cd-setup/action.yml
.github/workflows/ci-cd.yml

Changelog
---------
Checklist
---------

Replace runbook with github-secret

---

.github/workflows/ci-cd.yml
README.md
docs/docusaurus.config.ts
docs/src/pages/index.tsx

Changelog
---------
Checklist
---------
Reference
---------
- https://ngneat.github.io/elf/

Front page improvements

---

.github/actions/cd-setup/action.yml
.github/actions/ci-setup/action.yml

Changelog
---------
Checklist
---------

Centralize JDK setup in CI/CD

---

docs/docs/development.md

Changelog
---------
Checklist
---------
Reference
---------
- [Change image size in Docusaurus](https://stackoverflow.com/a/74158469)

Enhance image rendering

---

.github/workflows/ci-cd.yml

Changelog
---------
Checklist
---------

Add new upstream trigger

---

docs/docs/intro.mdx
docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx

Changelog
---------
Checklist
---------

Better elaboration on supporting JAX-RS only and not Spring

---

docs/docs/intro.mdx
docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx

Changelog
---------
Checklist
---------

Fix doc typo

---

docs/docs/intro.mdx
docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx

Changelog
---------
Checklist
---------

Better statement 'not supporting Spring'

---

docs/docs/setup.md
docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md

Changelog
---------
Checklist
---------

Add documentation on enabling auto unused import removal

---

docs/docs/elide/audit.md
docs/docs/elide/data-model.md
docs/docs/elide/datastores.mdx
docs/docs/elide/features.md
docs/docs/elide/openapi.md
docs/docs/elide/performance.md
docs/docs/elide/security.mdx

Changelog
---------
Checklist
---------

Enhance Elide Library index page

---

docker-compose.yml
docs/docs/configuration.md
src/main/java/com/paiondata/astraios/application/BinderFactory.java
src/main/java/com/paiondata/astraios/config/JpaDatastoreConfig.java
src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy

Changelog
---------
Checklist
---------

Make hibernate.hbm2ddl.auto configurable

---

.github/actions/ci-setup/action.yml
README.md

Changelog
---------
Checklist
---------

Add documentation site status badge

---

src/test/java/com/paiondata/astraios/HealthCheckIntegrationITSpec.java

Add IT test to actuator healthcheckadd test

---

src/test/java/com/paiondata/astraios/SpringbootITSpec.java
src/test/resources/payload/create-book.graphql
src/test/resources/payload/create-book.json
src/test/resources/payload/page-sort.graphql
src/test/resources/payload/page-sort.json
src/test/resources/payload/update-book.graphql
src/test/resources/payload/update-book.json

Change all payload file from json to graphql
